#!/bin/bash
set -e

cd /multiverse
if [ "$ENV" = 'development' ]; then
    pip3 install -r requirements.txt
    while true; do
        sleep 1
        python3.4 ./multiverse.py 0.0.0.0:3333 || true
    done
else
    uwsgi --ini /multiverse/uwsgi.ini "$@"
fi
